<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion><PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ManagedTests.cs" />
    <Compile Include="../../src/CarbonLuau/Persistence/*.cs" />
    <Compile Include="../../src/CarbonLuau.Core/Addons/CoreAddonPackage.cs" />
    <Compile Include="../../src/CarbonLuau.Core/Addons/PackageSources.cs" />
    <Compile Include="../../src/CarbonLuau.Core/Modules/ModulePath.cs" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
