<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion><PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/CarbonLuau/CarbonLuau.Native.cs" Link="CarbonLuau.Native.cs" />
    <Compile Include="../../src/CarbonLuau/CarbonLuau.Runtime.cs" Link="CarbonLuau.Runtime.cs" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
