set(CARBONLUAU_PERSISTENCE_TEST_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/persistence-fixtures" CACHE PATH "Task-owned local persistence fixture directory")
file(MAKE_DIRECTORY "${CARBONLUAU_PERSISTENCE_TEST_DIRECTORY}")
foreach(Suite Format CodecFault Backend BackendCrash Quota Corruption Physical WalAdmission)
    set(Sources "${CMAKE_CURRENT_SOURCE_DIR}/../tests/persistence/${Suite}Tests.cpp" src/persistence/Format.cpp)
    if(NOT Suite STREQUAL "Format" AND NOT Suite STREQUAL "CodecFault")
        list(APPEND Sources src/persistence/Backend.cpp)
    endif()
    add_executable(Persistence${Suite}Tests ${Sources})
    target_compile_features(Persistence${Suite}Tests PRIVATE cxx_std_17)
    target_include_directories(Persistence${Suite}Tests PRIVATE src/persistence)
    target_link_libraries(Persistence${Suite}Tests PRIVATE CarbonLuau.Sqlite)
    if(Suite STREQUAL "BackendCrash")
        target_compile_definitions(Persistence${Suite}Tests PRIVATE CARBONLUAU_PERSISTENCE_TESTING)
    endif()
    add_test(NAME Persistence${Suite} COMMAND Persistence${Suite}Tests)
    set_tests_properties(Persistence${Suite} PROPERTIES TIMEOUT 600 WORKING_DIRECTORY "${CARBONLUAU_PERSISTENCE_TEST_DIRECTORY}")
endforeach()
foreach(Fixture LostAck Hang)
    add_executable(StorageFixture${Fixture} src/persistence/Worker.cpp src/persistence/Backend.cpp src/persistence/Format.cpp)
    target_compile_features(StorageFixture${Fixture} PRIVATE cxx_std_17)
    target_link_libraries(StorageFixture${Fixture} PRIVATE CarbonLuau.Sqlite)
endforeach()
target_compile_definitions(StorageFixtureLostAck PRIVATE CARBONLUAU_STORAGE_FIXTURE=1)
target_compile_definitions(StorageFixtureHang PRIVATE CARBONLUAU_STORAGE_FIXTURE=2)
