set(CARBONLUAU_PERSISTENCE_TEST_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/persistence-fixtures" CACHE PATH "Task-owned local persistence fixture directory")
file(MAKE_DIRECTORY "${CARBONLUAU_PERSISTENCE_TEST_DIRECTORY}")
foreach(Suite Format CodecFault Sortable Backend BackendCrash Quota Corruption Physical WalAdmission Derived DerivedCrash DerivedPlan DerivedBudget)
    set(Sources "${CMAKE_CURRENT_SOURCE_DIR}/../tests/persistence/${Suite}Tests.cpp" src/persistence/Format.cpp)
    if(Suite STREQUAL "Sortable")
        list(APPEND Sources src/persistence/Sortable.cpp)
    elseif(NOT Suite STREQUAL "Format" AND NOT Suite STREQUAL "CodecFault")
        list(APPEND Sources src/persistence/Backend.cpp src/persistence/Derived.cpp src/persistence/Sortable.cpp)
    endif()
    add_executable(Persistence${Suite}Tests ${Sources})
    target_compile_features(Persistence${Suite}Tests PRIVATE cxx_std_17)
    target_include_directories(Persistence${Suite}Tests PRIVATE src/persistence)
    target_link_libraries(Persistence${Suite}Tests PRIVATE CarbonLuau.Sqlite)
    if(Suite STREQUAL "DerivedBudget")
        target_compile_definitions(Persistence${Suite}Tests PRIVATE
            CARBONLUAU_PERSISTENCE_BUDGET_TESTING
            CARBONLUAU_SQLITE_CERTIFICATE_SOURCE="${CARBONLUAU_SQLITE_SOURCE_DIR}/sqlite3.c"
            CARBONLUAU_DERIVED_CERTIFICATE_SOURCE="${CMAKE_CURRENT_SOURCE_DIR}/src/persistence/Derived.cpp")
    endif()
    if(Suite STREQUAL "Derived")
        target_compile_definitions(Persistence${Suite}Tests PRIVATE CARBONLUAU_PERSISTENCE_TIMING_TESTING)
    endif()
    if(Suite STREQUAL "BackendCrash" OR Suite STREQUAL "DerivedCrash" OR Suite STREQUAL "Physical")
        target_compile_definitions(Persistence${Suite}Tests PRIVATE CARBONLUAU_PERSISTENCE_TESTING)
    endif()
    add_test(NAME Persistence${Suite} COMMAND Persistence${Suite}Tests)
    set_tests_properties(Persistence${Suite} PROPERTIES TIMEOUT 600 WORKING_DIRECTORY "${CARBONLUAU_PERSISTENCE_TEST_DIRECTORY}")
endforeach()
add_test(NAME PersistenceDerivedFaults COMMAND PersistenceDerivedCrashTests --focused-faults)
set_tests_properties(PersistenceDerivedFaults PROPERTIES TIMEOUT 600
    WORKING_DIRECTORY "${CARBONLUAU_PERSISTENCE_TEST_DIRECTORY}")
add_executable(DerivedWorkerFixture ../tests/persistence/DerivedWorkerFixture.cpp ${CARBONLUAU_STORAGE_SOURCES})
target_compile_features(DerivedWorkerFixture PRIVATE cxx_std_17)
target_include_directories(DerivedWorkerFixture PRIVATE src/persistence)
target_link_libraries(DerivedWorkerFixture PRIVATE CarbonLuau.Sqlite)
foreach(Fixture LostAck Hang)
    add_executable(StorageFixture${Fixture} src/persistence/Worker.cpp ${CARBONLUAU_STORAGE_SOURCES})
    target_compile_features(StorageFixture${Fixture} PRIVATE cxx_std_17)
    target_link_libraries(StorageFixture${Fixture} PRIVATE CarbonLuau.Sqlite)
endforeach()
target_compile_definitions(StorageFixtureLostAck PRIVATE CARBONLUAU_STORAGE_FIXTURE=1)
target_compile_definitions(StorageFixtureHang PRIVATE CARBONLUAU_STORAGE_FIXTURE=2)
