<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>carbonluau-tooling</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CarbonLuau.Core/CarbonLuau.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../generated/tooling-metadata.json;../../api/carbonluau-api.json;../../tooling/language-server.json" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
